### PR TITLE
Person detection reference submission

### PR DESCRIPTION
**Pull request by njeffrie**
This is the current state of the visual wakewords person detection reference submisison. It currently crashes during __libc_init_array(), which leads me to believe we are somehow overwriting the array of function pointers used by libc to initialize the executable. I have verified that the same behavior occurs when the model is included in a minimal mbed project with only a main() function which reads a single byte out of the g_person_detection_model_data array.

I have also tried changing the array from const uint8_t .... to just uint8_t ... to move the model data from .rodata to .data and the error remains. I have also tried increasing the stack size to accommodate the entire model, but this also does not fix the issue. I have a sneaking suspicion this may be due to the compiler / linker incorrectly selecting the location to put the binary on device, perhaps due to a missing -mthumb flag or similar.

I figure it makes sense to share the project in its current state for two reasons:
1. Reference submission authors can integrate their submissions using the same code structure
2. Others in the TinyMLPerf group may have better insight into what is going on here

 I will continue to search for the solution to this issue and will update if I find a fix.

### CODE REVIEW

**Comment by njeffrie** [comment]
In case it's helpful, here are the steps to set up and run gdb on the L4R5ZI using OpenOCD:
[start GDB server in terminal 1]:
sudo apt install openocd
openocd -f board/st_nucleo_l4.cfg

[connect to server in terminal 2]:
<path-to-gdb>/gcc-arm-none-eabi-gdb BUILD/NUCLEO_L4R5ZI/GCC_ARM/person_detection.elf
[within gdb terminal]:
target remote localhost:3333

**Comment by colbybanbury** [comment]
Is this still failing or is it ready to submit?

**Comment by njeffrie** [comment]
I have tested running on NucleoL4R5Zi.

Follow up PR will be required to fully sort out input buffers supplied by the db command.

**Comment by colbybanbury** [comment]
This all looks great! I'll merge this now. Thanks Nat!

Can you open another PR to clean up the repo structure a bit? For example, move the vww folder into the reference_submission/person_detection folder. Also, we probably shouldn't have both an example_submission and reference_submission folder.

**Pull request merged**
